### ISSUE TITLE
panic when custom_config_output_dir does NOT exits.   

### ISSUE THREAD

**Issue by liangping** [open-libra/cli#4]
`RUST_BACKTRACE=1 ./open-libra config -o ~/config`
or `RUST_BACKTRACE=1 ./open-libra config -o ./config`

Both commands would not work properly. should create directories first if it does not exits.

```
thread 'main' panicked at 'Error opening file: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:999:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /Users/vsts/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /Users/vsts/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: rust_begin_unwind
             at src/libstd/panicking.rs:311
   9: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  10: core::result::unwrap_failed
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/macros.rs:18
  11: core::result::Result<T,E>::expect
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/result.rs:827
  12: libra_config::config::PersistableConfig::save_config
             at /Users/liangping/.cargo/git/checkouts/libra-0f33c279f44a04b6/5f8d6a2/config/src/config.rs:810
  13: open_libra::commands::config::builder::Builder::generate_peer_info
             at src/commands/config/builder.rs:209
  14: open_libra::commands::config::builder::Builder::build
             at src/commands/config/builder.rs:120
  15: <open_libra::commands::config::ConfigCmd as abscissa_core::runnable::Runnable>::run
             at src/commands/config.rs:25
  16: open_libra::commands::_DERIVE_Runnable_FOR_OpenLibraCmd::<impl abscissa_core::runnable::Runnable for open_libra::commands::OpenLibraCmd>::run
             at src/commands.rs:15
  17: <abscissa_core::command::entrypoint::EntryPoint<Cmd> as abscissa_core::runnable::Runnable>::run
             at /Users/liangping/.cargo/registry/src/github.com-1ecc6299db9ec823/abscissa_core-0.4.0/src/command/entrypoint.rs:52
  18: abscissa_core::application::Application::run
             at /Users/liangping/.cargo/registry/src/github.com-1ecc6299db9ec823/abscissa_core-0.4.0/src/application.rs:62
  19: abscissa_core::application::boot
             at /Users/liangping/.cargo/registry/src/github.com-1ecc6299db9ec823/abscissa_core-0.4.0/src/application.rs:197
  20: open_libra::main
             at src/bin/open-libra/main.rs:10
  21: std::rt::lang_start::{{closure}}
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/rt.rs:64
  22: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  23: std::panicking::try::do_call
             at src/libstd/panicking.rs:296
  24: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:82
  25: std::panicking::try
             at src/libstd/panicking.rs:275
  26: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  27: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  28: std::rt::lang_start
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/rt.rs:64
  29: open_libra::main

```

**Comment by tarcieri** [comment]
I think you fixed this with #5
